import {AppUI} from './AppUI'
import {GeneralProvider} from '../GeneralContext'

// const exercises = [
//   {name:'Walking',description:' Search for a wide place to walk and do it at a constant rhytm moving your arms following your steps to generate a complete motion of your body',benefits:['Improves cardiovascular health','Reduces stress and anxiety','Increases energy levels'],suggestedSeries:1,suggestedReps:1,suggestedTime:['0H','30M','0S'],imgPath:'https://th.bing.com/th/id/OIG4.bmGx810MKzvLKd40rlg.?w=1024&h=1024&rs=1&pid=ImgDetMain'},
//   {name:'Push ups',description:' A traditional push-up is a bodyweight exercise targeting the upper body,, engaging chest,, shoulders,, and triceps, performed by lowering and raising the body using arm strength',benefits:['Strengthen the chest,, shoulders and arms',' Promote better posture',' Increase overall upper body strenght and endurance'],suggestedSeries:3,suggestedReps:8-10,suggestedTime:['0H','0M','0S'],imgPath:'https://th.bing.com/th/id/OIG4.tp5KRY5TI4BEgOy1_W.G?w=1024&h=1024&rs=1&pid=ImgDetMain'},
//   {name:'Running',description:' Engage in continuous running at a moderate to high intensity, focusing on maintaining proper form and breathing rhythm',benefits:['Improves cardiovascular fitness',' Burns calories',' Boosts mood and mental clarity'],suggestedSeries:1,suggestedReps:1,suggestedTime:['0H','20M','0S'],imgPath:'https://th.bing.com/th/id/OIG3.xFkAiWLAjNhRFaFdQnCA?w=1024&h=1024&rs=1&pid=ImgDetMain'},
//   {name:'Squats',description:' Stand with feet shoulder-width apart,, lower hips down and back as if sitting into a chair,, keeping chest up and knees behind toes,, then return to standing position',benefits:['Strengthens lower body muscles (quadriceps, hamstrings, glutes)',' Improves balance and mobility',' Enhances core stability'],suggestedSeries:3,suggestedReps:10-12,suggestedTime:['0H','0M','0S'],imgPath:'https://th.bing.com/th/id/OIG4.9pK0jMbxQCSHnIsWxU2j?pid=ImgGn'},
//   {name:'Cycling',description:' Ride a bicycle at a steady pace, adjusting resistance as needed, focus on maintaining proper form and breathing',benefits:['Strengthens leg muscles',' Increases cardiovascular endurance',' Low-impact exercise reduces stress on joints'],suggestedSeries:1,suggestedReps:1,suggestedTime:['0H','30M','0S'],imgPath:'https://th.bing.com/th/id/OIG1.NvEvRf.yw.hNLqneY23x?pid=ImgGn'},
//   {name:'Pull ups',description:' Hang from a bar with hands shoulder-width apart,, pull body up until chin clears the bar,, then lower back down with control',benefits:['Builds upper body strength (back,, shoulders,, arms),, Improves grip strength','',' Enhances upper body muscle definition'],suggestedSeries:3,suggestedReps:5-8,suggestedTime:['0H','0M','0S'],imgPath:'https://th.bing.com/th/id/OIG3.tbctY5NMc0RflcpaEaR4?w=1024&h=1024&rs=1&pid=ImgDetMain'},
//   {name:'Lunges',description:' Step forward with one leg, lowering hips until both knees are bent at 90-degree angles, then push back to starting position and repeat on the other leg',benefits:['Strengthens lower body muscles (quadriceps, hamstrings, glutes)',' Improves balance and stability',' Enhances hip flexibility'],suggestedSeries:3,suggestedReps:10-12,suggestedTime:['0H','0M','0S'],imgPath:'https://th.bing.com/th/id/OIG3.oUPropCQWMEtwENbUFQR?pid=ImgGn'},
//   {name:'Jumping jacks',description:' Start with feet together and arms at sides, jump up while spreading legs and raising arms overhead, then return to starting position',benefits:['Improves cardiovascular fitness',' Burns calories',' Engages multiple muscle groups'],suggestedSeries:3,suggestedReps:30-60,suggestedTime:['0H','0M','0S'],imgPath:'https://th.bing.com/th/id/OIG4.43pdVwZrfy7RjmEHR4Q8?pid=ImgGn'},
//   {name:'Plank',description:' Start in a push-up position,, lower body to elbows and hold a straight line from head to heels,, engaging core muscles',benefits:['Strengthens core muscles',' Improves posture',' Enhances overall stability and balance'],suggestedSeries:3,suggestedReps:1,suggestedTime:['0H','0M','40S'],imgPath:'https://th.bing.com/th/id/OIG4.HzgIwrc0G6WfslY88ImK?pid=ImgGn'},
//   {name:'Bench press',description:' Lie on a flat bench with feet flat on the floor, grasp the barbell with hands slightly wider than shoulder-width apart, lower bar to chest, then push back up',benefits:['Builds upper body strength (chest, shoulders, triceps)',' Improves muscular endurance',' Enhances chest muscle definition'],suggestedSeries:3,suggestedReps:8-10,suggestedTime:['0H','0M','0S'],imgPath:'https://th.bing.com/th/id/OIG4.HuaH.QfeV.2Z.hF9X2SN?pid=ImgGn'},
//   {name:'Deadlifts',description:' Stand with feet hip-width apart,, grasp barbell with hands shoulder-width apart,, lower bar to floor while keeping back flat and chest up,, then stand back up',benefits:['Strengthens posterior chain muscles (hamstrings, glutes, lower back)',' Enhances grip strength',' Improves overall strength and power'],suggestedSeries:3,suggestedReps:5-8,suggestedTime:['0H','0M','0S'],imgPath:'https://th.bing.com/th/id/OIG4.gkZDGcPI_HX5Eqscz64_?pid=ImgGn'},
//   {name:'Russian twists',description:' Sit on the floor with knees bent and feet elevated, lean back slightly, hold a weight or medicine ball with both hands, twist torso from side to side',benefits:['Targets oblique muscles',' Strengthens core muscles',' Improves rotational stability and balance'],suggestedSeries:3,suggestedReps:10-12,suggestedTime:['0H','0M','0S'],imgPath:'https://th.bing.com/th/id/OIP.337DNQrzG3D95T_QSbCbtwHaHa?w=205&h=205&c=7&r=0&o=5&dpr=1.3&pid=1.7'},
//   {name:'Leg press',description:' Sit on a leg press machine with feet shoulder-width apart on the platform,, push platform away by extending legs,, then return to starting position',benefits:['Strengthens leg muscles (quadriceps, hamstrings, glutes)',' Improves lower body strength and endurance',' Reduces risk of lower body injuries'],suggestedSeries:3,suggestedReps:10-12,suggestedTime:['0H','0M','0S'],imgPath:'https://th.bing.com/th/id/OIG4.9n65widHYgTYNaAu0anU?w=1024&h=1024&rs=1&pid=ImgDetMain'},
//   {name:'Dumbbell shoulder press',description:' Stand with feet hip-width apart,, hold dumbbells at shoulder height with palms facing forward,, press weights overhead until arms are fully extended,, then lower back down',benefits:['Targets shoulder muscles (deltoids)',' Improves shoulder strength and stability',' Enhances upper body muscular balance'],suggestedSeries:3,suggestedReps:8-10,suggestedTime:['0H','0M','0S'],imgPath:'https://th.bing.com/th/id/OIG3.coe7XO5SsLEFh8q4OSbL?pid=ImgGn'},
//   {name:'Crunches',description:' Lie on your back with knees bent and feet flat on the floor, place hands behind head, lift shoulders off the floor using abdominal muscles, then lower back down',benefits:['Targets abdominal muscles (rectus abdominis)',' Improves core strength and stability',' Enhances abdominal muscle definition'],suggestedSeries:3,suggestedReps:10-12,suggestedTime:['0H','0M','0S'],imgPath:'https://th.bing.com/th/id/OIG4.TtRHVUZ8GMcZ3GnlvFw8?pid=ImgGn'},
//   ]
// const routines = [
//   {name: 'default routine 1',description:'Default description 1 Default description 1 Default description 1 Default description 1 ',exercises:['Squats','Running','Crunches'],series:[3,1,3],reps:[8,1,10],time:[['0H','0M','0S'],['0H','0M','0S'],['0H','25M','0S']]},
//   {name: 'default routine 2',description:'Default description 2 Default description 2 Default description 2 Default description 2 ',exercises:['Walking','Bench press','Dumbbell shoulder press'],series:[1,2,3],reps:[1,8,10],time:[['0H','30M','0S'],['0H','0M','0S'],['0H','0M','0S']]},
//   {name: 'default routine 3',description:'Default description 3 Default description 3 Default description 3 Default description 3 ',exercises:['Push ups','Running','Plank'],series:[3,1,3],reps:[8,1,1],time:[['0H','0M','0S'],['1H','0M','0S'],['0H','0M','45S']]},
//   {name: 'default routine 4',description:'Default description 4 Default description 4 Default description 4 Default description 4 ',exercises:['Cycling','Pull ups','Lunges'],series:[1,4,3],reps:[1,3,10],time:[['0H','40M','0S'],['0H','0M','0S'],['0H','0M','0S']]},
//   {name: 'default routine 5',description:'Default description 5 Default description 5 Default description 5 Default description 5 ',exercises:['Jumping jacks','Deadlifts','Crunches'],series:[3,5,3],reps:[8,1,10],time:[['0H','0M','0S'],['0H','0M','0S'],['0H','0M','0S']]},
//   {name: 'default routine 6',description:'Default description 6 Default description 6 Default description 6 Default description 6 ',exercises:['Russian twists','Running','Leg press'],series:[3,1,3],reps:[8,1,10],time:[['0H','0M','0S'],['0H','35M','0S'],['0H','0M','0S']]},
//   {name: 'default routine 7',description:'Default description 7 Default description 7 Default description 7 Default description 7 ',exercises:['Crunches','Running','Dumbbell shoulder press'],series:[3,1,3],reps:[8,1,9],time:[['0H','0M','0S'],['0H','23M','0S'],['0H','0M','0S']]},
//   {name: 'default routine 8',description:'Default description 8 Default description 8 Default description 8 Default description 8 ',exercises:['Deadlifts','Plank','Crunches'],series:[3,2,3],reps:[8,1,10],time:[['0H','0M','0S'],['0H','0M','50S'],['0H','0M','0S']]},
//   {name: 'default routine 9',description:'Default description 9 Default description 9 Default description 9 Default description 9 ',exercises:['Squats','Deadlifts','Plank'],series:[3,3,3],reps:[8,5,1],time:[['0H','0M','0S'],['0H','0M','0S'],['0H','0M','30S']]},
//   {name: 'default routine 10',description:'Default description 10 Default description 10 Default description 10 Default description 10 ',exercises:['Plank','Running','Deadlifts'],series:[3,1,3],reps:[1,1,10],time:[['0H','0M','30S'],['0H','30M','0S'],['0H','0M','0S']]},
//   {name: 'default routine 11',description:'Default description 11 Default description 11 Default description 11 Default description 11 ',exercises:['Deadlifts','Plank','Crunches'],series:[3,3,3],reps:[8,1,10],time:[['0H','0M','0S'],['0H','0M','40S'],['0H','0M','0S']]},
// ]
// localStorage.setItem('exercises',JSON.stringify(exercises))
// localStorage.setItem('routines',JSON.stringify(routines))

function App() {
  return (
      <GeneralProvider>
        <AppUI/>
      </GeneralProvider>
  );
}

export default App;
